# Бибилиотека NumPy

Библиотека NumPy предназначена для быстрой обработки однородных (в основном числовых) массивов.

Основным объектом библиотеки является многомерный массив ndarray. Этот массив может быть создан из списка или другого итерируемого объекта Python.

In [1]:
import numpy as np

In [2]:
l = [[1,2,3], [4,5,6]]
nd = np.array(l)
nd

array([[1, 2, 3],
       [4, 5, 6]])

Массив имеет ряд функций для работы с его формой.

In [3]:

print(nd.ndim) # Размерность массива
print(nd.shape) # Количество элементов по каждой размерности
print(nd.dtype) # Тип элементов
print(nd.data) # Буфер с элементами


2
(2, 3)
int64


Массивы numpy позволяют проводить арифметические операции быстрее, чем над списками. Помимо этого, для этих массивов есть масса стандартных математических функций.

In [4]:
l = list(range(1000000))
nd = np.array(range(1000000))

In [5]:
%%time
sum(l)

CPU times: user 8.6 ms, sys: 238 µs, total: 8.83 ms
Wall time: 8.89 ms


499999500000

In [6]:
%%time
nd.sum()

CPU times: user 1.56 ms, sys: 0 ns, total: 1.56 ms
Wall time: 1.31 ms


499999500000

Сравним скорость работы скалярного произведения.

In [7]:
%%time
s = 0
for a in l:
    s += a * a
print(s)

333332833333500000
CPU times: user 128 ms, sys: 0 ns, total: 128 ms
Wall time: 127 ms


In [8]:
%%time
s = sum(map(lambda x: x*x, l))

CPU times: user 80.8 ms, sys: 0 ns, total: 80.8 ms
Wall time: 79.5 ms


In [9]:
%%time
nd.dot(nd)

CPU times: user 0 ns, sys: 1.41 ms, total: 1.41 ms
Wall time: 1.1 ms


333332833333500000

Массив может создаваться по-разному в зависимости от типа объектов. Желаемый тип можно передать при создании в параметре dtype.

In [10]:
np.array( [ [1,2], [3,4] ], dtype=np.int32 )

array([[1, 2],
       [3, 4]], dtype=int32)

In [51]:
np.array( [ [complex(1, 2),2], [3,4] ], dtype=complex )

array([[1.+2.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [12]:
np.array( [ [1.1,2.2], [3.3,4.4] ], dtype=np.float)

array([[1.1, 2.2],
       [3.3, 4.4]])

# Индексирование массивов

Индекс пишется в единых квадратных скобках через запятую. Порядок следования индексов - как в С++.

In [13]:
nd = np.array([[1,2,3], [4,5,6]])
nd[0, 1]

2

Как и в случае со списками Python, можно использовать срезы для создания прямоугольных фрагментов. Срезы подчиняются темм же правилам.

In [14]:
nd[0:1, 1:3]

array([[2, 3]])

In [15]:
nd[1, 0:3:2]

array([4, 6])

Срезы могут использоваться не только для чтения элементов, но и для записи.

In [16]:
nd[1, 0:3:2] = -1
nd

array([[ 1,  2,  3],
       [-1,  5, -1]])

# Создание массива и изменение его размеров
Для создания стандартных массивов библиотека предоставляет массу функций.

In [55]:
np.zeros((5,5), dtype=np.int32) # Функция создает массив заданной размерности, заполненный нулями.

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [18]:
np.ones((5,5)) # Функция создает массив заданной размерности, заполненный нулями.

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.linspace( 0, 2, 9 ) # Массив из 9 элементов от 0 до 2 включительно.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
np.arange(1, 10, 2) # Аналог стандартного range

array([1, 3, 5, 7, 9])

In [21]:
%%time
nd = np.array(range(1000000))

CPU times: user 149 ms, sys: 32.2 ms, total: 181 ms
Wall time: 181 ms


In [73]:
%%time
nd = np.arange(1000000)

CPU times: user 5.23 ms, sys: 525 µs, total: 5.75 ms
Wall time: 3.13 ms


Для преобразования размерности массива используется функция `reshape`.

In [23]:
np.reshape(nd, (1000, 1000))

array([[     0,      1,      2, ...,    997,    998,    999],
       [  1000,   1001,   1002, ...,   1997,   1998,   1999],
       [  2000,   2001,   2002, ...,   2997,   2998,   2999],
       ...,
       [997000, 997001, 997002, ..., 997997, 997998, 997999],
       [998000, 998001, 998002, ..., 998997, 998998, 998999],
       [999000, 999001, 999002, ..., 999997, 999998, 999999]])

In [75]:
np.reshape(nd, (200, 5000))

array([[     0,      1,      2, ...,   4997,   4998,   4999],
       [  5000,   5001,   5002, ...,   9997,   9998,   9999],
       [ 10000,  10001,  10002, ...,  14997,  14998,  14999],
       ...,
       [985000, 985001, 985002, ..., 989997, 989998, 989999],
       [990000, 990001, 990002, ..., 994997, 994998, 994999],
       [995000, 995001, 995002, ..., 999997, 999998, 999999]])

Один из параметров размера массива может равняться -1. В этом случае он ыводится из резмеров массива.

In [25]:
np.array([[1,2,3],[4,5,6]]).reshape((1, -1))

array([[1, 2, 3, 4, 5, 6]])

In [26]:
np.array([[1,2,3],[4,5,6]]).reshape((-1, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [27]:
np.array([[1,2,3],[4,5,6]]).reshape((2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

Функция `meshgrid` создает массивы с декартовым произведением индексов. Количество массивов на выходе равно количеству массивов на входе, то есть размерности пространств совпадают. Параметр `indexing` позволяет менять порядок следования индексов (принимает значения 'xy' или 'ij').

In [76]:
np.meshgrid(np.arange(5), np.arange(20, 23), indexing='xy')

[array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]), array([[20, 20, 20, 20, 20],
        [21, 21, 21, 21, 21],
        [22, 22, 22, 22, 22]])]

# Арифметические и другие операции

В состав библиотеки входят функции для расчета арифметических, тригонометрических, логических, матричных и других функций. 

С полным списком функций можно ознакомиться [здесь](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

In [29]:
nd = np.arange(1000000)

In [30]:
(nd * nd + nd) / nd

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        nan, 2.00000e+00, 3.00000e+00, ..., 9.99998e+05,
       9.99999e+05, 1.00000e+06])

In [31]:
m2 = np.meshgrid(np.arange(5), np.arange(20, 23), indexing='ij')
m2[0] + 3 * m2[1]

array([[60, 63, 66],
       [61, 64, 67],
       [62, 65, 68],
       [63, 66, 69],
       [64, 67, 70]])

In [32]:
np.around(((nd * nd + nd) / nd)) # Округление результатов.

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        nan, 2.00000e+00, 3.00000e+00, ..., 9.99998e+05,
       9.99999e+05, 1.00000e+06])

In [33]:
np.hypot(nd, nd) # Возвращает гипотенузы для заданных массивов катетов.

array([0.00000000e+00, 1.41421356e+00, 2.82842712e+00, ...,
       1.41420932e+06, 1.41421073e+06, 1.41421215e+06])

In [34]:
np.cumsum(nd[:100]) # Кумулятивная сумма элементов.

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926,
       3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828,
       3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851,
       4950])

In [35]:
np.log10(nd[1:10])

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [36]:
np.sin(nd)

array([ 0.        ,  0.84147098,  0.90929743, ...,  0.21429647,
       -0.70613761, -0.97735203])

In [37]:
np.isnan(((nd * nd + nd) / nd))

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ True, False, False, ..., False, False, False])

Логические операции могут использовать специальные функции (`logical_and`, `logical_or`, `logical_not`, `logical_xor`, `greater`, `greater_equal`, ...) или операторы битовой логики.

In [38]:
np.isnan(((nd * nd + nd) / nd)) & np.greater(nd * 2, nd) # Поэлементное логическое и.

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([False, False, False, ..., False, False, False])

In [80]:
# Оператор свертки по массиву conv_oper сигнала nd1.
nd1 = np.zeros(100)
nd1[1] = 1
nd1[20] = 10
nd1[21] = 9
nd1[30] = 20
nd1[31] = 25

conv_oper = np.array([1, 2, 3, 4, -3, -2, -1])
np.convolve(nd1, conv_oper)

array([   0.,    1.,    2.,    3.,    4.,   -3.,   -2.,   -1.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,   10.,   29.,   48.,   67.,    6.,  -47.,  -28.,
         -9.,    0.,    0.,   20.,   65.,  110.,  155.,   40., -115.,
        -70.,  -25.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.])

# Операции линейной алгебры

Список операций можно найти [здесь](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html).

In [40]:
nd = np.arange(1000000)
nd4 = nd.reshape((1000, 1000))

In [41]:
np.linalg.norm(nd[:1000])

18243.72494859534

In [42]:
%%time
_ = np.linalg.qr(nd4)

CPU times: user 1.02 s, sys: 595 ms, total: 1.62 s
Wall time: 242 ms


In [43]:
%%time
_ = np.linalg.svd(nd4)

CPU times: user 3 s, sys: 1.33 s, total: 4.32 s
Wall time: 626 ms


In [44]:
np.linalg.solve(nd4, nd[1000: 2000])

LinAlgError: Singular matrix

# Генерация случайных чисел
Библиотека numpy предоставляет гораздо более удобные функции ля генерации случайных чисел.

Список функций находится [здесь](https://docs.scipy.org/doc/numpy/reference/random/generator.html).

In [45]:
np.random.normal(10, 2, 15) # Генерирует 15 нормально распределенных чисел со средним в 10 и дисперсией 2

array([10.29750686, 12.67657212,  8.78261079,  8.96963826,  8.2404639 ,
        6.89984443,  8.58151565,  6.78303845,  9.4202015 ,  9.77071945,
        9.61214023, 10.79054658,  7.91297415,  9.67433187,  8.98527444])

In [46]:
# Генерирует 15 чисел, распределенных по лог-нормальному закону, мат. ожидание = 10, дисперсиея = 2
np.random.lognormal(10, 2, 15)

array([  6051.12493043,   4312.73813577,   2996.13692551, 232825.12900657,
        13253.6891371 ,  50597.63637827, 102317.69958821,  23188.08104887,
         2565.60825646,   4040.93992939,   7374.12963224,   6133.77323358,
         7707.9042429 ,    739.13887478, 105617.45119635])

In [47]:
# Генерирует 15 чисел, распределенных по бета-распределению, с параметрами 10 и 2
np.random.beta(10, 2, 15) 

array([0.57089499, 0.92698999, 0.8153385 , 0.76879395, 0.82793235,
       0.92302417, 0.92279243, 0.95349757, 0.94455639, 0.61179676,
       0.80883903, 0.88845423, 0.92249265, 0.95607397, 0.93910564])